name: job-crawler
services:
- name: api
  source_dir: /
  github:
    branch: playgroud
    deploy_on_push: true
    repo: jgabrielsantosc/scraper-jobboard
  build_command: npm ci && npm run build:api
  run_command: npm run start:prod
  http_port: 3001
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
    - path: /api
  envs:
    - key: NODE_ENV
      value: production
    - key: PORT
      value: "3001"

- name: worker
  source_dir: /
  github:
    branch: playgroud
    deploy_on_push: true
    repo: jgabrielsantosc/scraper-jobboard
  build_command: npm ci && npm run build:api
  run_command: npm run start:worker
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
    - key: NODE_ENV
      value: production

databases:
- engine: PG
  name: postgres
  num_nodes: 1
  size: db-s-dev-database
  version: "15"

- engine: REDIS
  name: redis
  num_nodes: 1
  size: db-s-dev-database
  version: "7" 